name: Docker

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        CMAKE_BUILD_TYPE: [RelWithDebInfo]
        compiler: [ {CXX: g++, CC: gcc}, {CXX: clang++, CC: clang} ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: docker build --ulimit memlock=-1:-1 --build-arg CC=${{ matrix.compiler.CC }} --build-arg CXX=${{ matrix.compiler.CXX }} --build-arg CMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }} --build-arg CI=true --file docker/Dockerfile .
