name: Docker

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - CC: clang
            CXX: clang++
          - CC: gcc
            CXX: g++

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: docker build --build-arg CC=${{ matrix.CC }} --build-arg CXX=${{ matrix.CXX }} --file docker/Dockerfile .
