name: Docker

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        CMAKE_BUILD_TYPE: [RelWithDebInfo, Debug]
        compiler: [ {CXX: g++, CC: gcc}, {CXX: clang++, CC: clang} ]

    runs-on: ubuntu-latest

    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - run: docker build --build-arg CC=${{ matrix.compiler.CC }} --build-arg CXX=${{ matrix.compiler.CXX }} --build-arg CMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }} --file docker/Dockerfile .
